language: ruby
rvm:
- 2.4.1
- 2.2.2
- 2.1.0
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-3

before_install:
- gem install bundler -v 1.12
- gem update --system
- bundle --version
- gem --version

install:
- bundle _1.12.0_ install --with "$GEMSETS"

script:
- bundle _1.12.0_ exec rake
