language: ruby
rvm:
- 2.4.1
- 2.2.2
- 2.1.0
- 2.0.0
- 1.9.3
- jruby-19mode

install:
- bundle install --with "$GEMSETS"

jobs:
  include:
    - stage: test
      rvm: 2.4.1
      script: bundle exec rubocop lib/

script:
- bundle exec rake spec
