language: ruby
rvm:
- 2.4.1
- 2.2.2
- 2.1.0
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-3
notifications:
  hipchat:
    rooms:
      secure: pxU3BZq7lQKFdbEzzysH9tFzHYPWh/AfqJ3yG1lois4D4UW+29ranTtOPR8qUChXSM6KhC4uOXwekTDOQTTALO95483gEYyGvXCTtomhSrZEBCv7Ngl9IHRtPU0nPuuQBo2v95S/KlInuEsL/gwaKQO8iXItevdJZnRChFaKDuA=
