require "bugsnag/api"
require "webmock/rspec"
require "faker"

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.expect_with :rspec do |c|
    c.syntax = :expect
  end
end

WebMock.allow_net_connect!

def auth_token_client
  Bugsnag::Api.configure do |config|
    config.auth_token = ENV["BUGSNAG_TEST_AUTH_TOKEN"]
    config.endpoint = ENV["BUGSNAG_TEST_ENDPOINT"] if ENV["BUGSNAG_TEST_ENDPOINT"]
  end

  Bugsnag::Api.client
end

def basic_auth_client
  Bugsnag::Api.configure do |config|
    config.email = ENV["BUGSNAG_TEST_EMAIL"]
    config.password = ENV["BUGSNAG_TEST_PASSWORD"]
    config.endpoint = ENV["BUGSNAG_TEST_ENDPOINT"] if ENV["BUGSNAG_TEST_ENDPOINT"]
  end

  Bugsnag::Api.client
end

def bugsnag_url(path)
  URI.join(Bugsnag::Api.configuration.endpoint, path).to_s
end

def stub_get(url)
  stub_request(:get, bugsnag_url(url))
end

def test_bugsnag_account
  ENV["BUGSNAG_TEST_ACCOUNT"]
end

def test_bugsnag_comment
  ENV["BUGSNAG_TEST_COMMENT"]
end

def test_bugsnag_error
  ENV["BUGSNAG_TEST_ERROR"]
end

def test_bugsnag_event
  ENV["BUGSNAG_TEST_EVENT"]
end

def test_bugsnag_project
  ENV["BUGSNAG_TEST_PROJECT"]
end

def test_bugsnag_user
  ENV["BUGSNAG_TEST_USER"]
end
