name: Tests

on: [push, pull_request]

jobs:
  specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '3.0']

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake spec

  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - run: bundle exec rubocop lib/

  # Ruby 1.9 and 2.0 aren't supported by setup-ruby so we have to use Docker instead
  legacy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['1.9', '2.0']

    container: ruby:${{ matrix.ruby-version }}

    steps:
      - uses: actions/checkout@v2

      - run: bundle install

      - run: bundle exec rake spec
